-- these have been auto generated but you can add your own if you follow this convention.
-- buddy_privacy_changed will become buddy-privacy-changed

return [[void buddy_status_changed ( PurpleBuddy * , PurpleStatus * , PurpleStatus * );
void buddy_privacy_changed ( PurpleBuddy * );
void buddy_idle_changed ( PurpleBuddy * , int , int );
void buddy_signed_on ( PurpleBuddy * );
void buddy_signed_off ( PurpleBuddy * );
void buddy_got_login_time ( PurpleBuddy * );
void blist_node_added ( PurpleBlistNode * );
void blist_node_removed ( PurpleBlistNode * );
void buddy_added ( PurpleBuddy * );
void buddy_removed ( PurpleBuddy * );
void buddy_icon_changed ( PurpleBuddy * );
void update_idle (  );
void blist_node_extended_menu ( PurpleBlistNode * , GList * *  );
void blist_node_aliased ( PurpleBlistNode * , const char * );
void buddy_caps_changed ( PurpleBuddy * , int , int );
void certificate_stored ( PurpleCertificatePool * , const char * );
void certificate_deleted ( PurpleCertificatePool * , const char * );
void cipher_added ( PurpleCipher * );
void cipher_removed ( PurpleCipher * );
void cmd_added ( const char * , int , int );
void cmd_removed ( const char * );
bool writing_im_msg ( PurpleAccount * , const char * , char * * , PurpleConversation * , unsigned int );
void wrote_im_msg ( PurpleAccount * , const char * , const char * , PurpleConversation * , unsigned int );
void sent_attention ( PurpleAccount * , const char * , PurpleConversation * , unsigned int );
void got_attention ( PurpleAccount * , const char * , PurpleConversation * , unsigned int );
void sending_im_msg ( PurpleAccount * , const char * , char * * );
void sent_im_msg ( PurpleAccount * , const char * , const char * );
bool receiving_im_msg ( PurpleAccount * , char * * , char * * , PurpleConversation * , unsigned int * );
void received_im_msg ( PurpleAccount * , const char * , const char * , PurpleConversation * , unsigned int );
void blocked_im_msg ( PurpleAccount * , const char * , const char * , unsigned int , unsigned int );
bool writing_chat_msg ( PurpleAccount * , const char * , char * * , PurpleConversation * , unsigned int );
void wrote_chat_msg ( PurpleAccount * , const char * , const char * , PurpleConversation * , unsigned int );
void sending_chat_msg ( PurpleAccount * , char * * , unsigned int );
void sent_chat_msg ( PurpleAccount * , const char * , unsigned int );
bool receiving_chat_msg ( PurpleAccount * , char * * , char * * , PurpleConversation * , unsigned int * );
void received_chat_msg ( PurpleAccount * , const char * , const char * , PurpleConversation * , unsigned int );
void conversation_created ( PurpleConversation * );
void conversation_updated ( PurpleConversation * , unsigned int );
void deleting_conversation ( PurpleConversation * );
void buddy_typing ( PurpleAccount * , const char * );
void buddy_typed ( PurpleAccount * , const char * );
void buddy_typing_stopped ( PurpleAccount * , const char * );
bool chat_buddy_joining ( PurpleConversation * , const char * , unsigned int );
void chat_buddy_joined ( PurpleConversation * , const char * , unsigned int , bool );
void chat_buddy_flags ( PurpleConversation * , const char * , unsigned int , unsigned int );
bool chat_buddy_leaving ( PurpleConversation * , const char * , const char * );
void chat_buddy_left ( PurpleConversation * , const char * , const char * );
void deleting_chat_buddy ( PurpleConvChatBuddy * );
void chat_inviting_user ( PurpleConversation * , const char * , char * * );
void chat_invited_user ( PurpleConversation * , const char * , const char * );
int chat_invited ( PurpleAccount * , const char * , const char * , const char * , void * );
void chat_invite_blocked ( PurpleAccount * , const char * , const char * , const char * , GHashTable *  );
void chat_joined ( PurpleConversation * );
void chat_join_failed ( PurpleConnection * , void * );
void chat_left ( PurpleConversation * );
void chat_topic_changed ( PurpleConversation * , const char * , const char * );
void cleared_message_history ( PurpleConversation * );
void conversation_extended_menu ( PurpleConversation * , GList * *  );
bool uri_handler ( const char * , const char * , GHashTable *  );
void quitting (  );
bool dbus_method_called ( void * , void * );
void dbus_introspect ( void * * );
void file_recv_accept ( PurpleXfer * );
void file_send_accept ( PurpleXfer * );
void file_recv_start ( PurpleXfer * );
void file_send_start ( PurpleXfer * );
void file_send_cancel ( PurpleXfer * );
void file_recv_cancel ( PurpleXfer * );
void file_send_complete ( PurpleXfer * );
void file_recv_complete ( PurpleXfer * );
void file_recv_request ( PurpleXfer * );
void image_deleting ( PurpleStoredImage * );
const char * log_timestamp ( PurpleLog * , int , int64_t , bool );
void displaying_email_notification ( const char * , const char * , const char * , const char * );
void displaying_emails_notification ( void * , void * , void * , void * , unsigned int );
void displaying_userinfo ( PurpleAccount * , const char * , PurpleNotifyUserInfo * );
void plugin_load ( PurplePlugin * );
void plugin_unload ( PurplePlugin * );
void savedstatus_changed ( PurpleSavedStatus * , PurpleSavedStatus * );
void savedstatus_added ( PurpleSavedStatus * );
void savedstatus_deleted ( PurpleSavedStatus * );
void savedstatus_modified ( PurpleSavedStatus * );
bool playing_sound_event ( int , PurpleAccount * );
void account_modified ( PurpleAccount * );
void gtkblist_hiding ( PurpleBuddyList * );
void gtkblist_unhiding ( PurpleBuddyList * );
void gtkblist_created ( PurpleBuddyList * );
void drawing_tooltip ( PurpleBlistNode * , GString *  , bool );
const char * drawing_buddy ( PurpleBuddy * );
const char * conversation_timestamp ( PurpleConversation * , int , int64_t , bool );
bool displaying_im_msg ( PurpleAccount * , const char * , char * * , PurpleConversation * , int );
void displayed_im_msg ( PurpleAccount * , const char * , const char * , PurpleConversation * , int );
bool displaying_chat_msg ( PurpleAccount * , const char * , char * * , PurpleConversation * , int );
void displayed_chat_msg ( PurpleAccount * , const char * , const char * , PurpleConversation * , int );
void conversation_switched ( PurpleConversation * );
bool chat_nick_autocomplete ( PurpleConversation * );
bool chat_nick_clicked ( PurpleConversation * , const char * , unsigned int );
]]